<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to Ian\'s Resume Web Page'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Get ready to be impressed! Click on the button below view my github page :)'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/cmius/myresume" target="_blank"><?php echo $this->translate('Start Here') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Biodata') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Know everything about me from my full name to my hobbies. This is a well organised and intuitive biodata. This is no TLDR type which makes you bored.'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('Check me out! :)') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Education') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Keep track my education path from the age of 6 until the age where I graduated my Bachelors degree'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore Ian\'s Education') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Work, Experience & Project(s)') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Here lists my previous work experience and as well of project since the beginning of my involvement in the IT & Software development world!'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Show me your Experience!') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
